version: 2

jobs:
  build:
    working_directory: /home/reaction

    docker:
      - image: node:8

    environment:
      - METEOR_ALLOW_SUPERUSER: true
      - TOOL_NODE_FLAGS: "--max-old-space-size=4096"

    steps:
      # - setup_remote_docker
      - checkout

      # install OS dependencies
      - restore_cache:
          name: Restoring Meteor cache
          key: meteor

      - run: .circleci/install.sh

      - save_cache:
          name: Saving Meteor to cache
          key: meteor
          paths:
            - ~/.meteor

      # install app dependencies
      - run: meteor npm install

      # run tests
      - restore_cache:
          name: Restoring Meteor dev_bundle cache
          key: dev_bundle

      # run reaction tests
      - run: .circleci/tests.sh

      - save_cache:
          name: Saving Meteor dev_bundle to cache
          key: dev_bundle
          paths:
            - /home/reaction/.meteor/local